ui/pr.go
ui/section.go
ui/styles.go
ui/tabs.go
ui/ui.go

Slight UI improvements

---

ui/pr.go
ui/sidebar.go
ui/styles.go

Checks Pill in sidebar

---

config/parser.go
ui/modelUtils.go
ui/section.go
ui/tabs.go
ui/ui.go

New config structure:
```yaml
prSections:
- title: My Pull Requests
filters: is:open author:@me
- title: Needs My Review
filters: is:open review-requested:@me
- title: Subscribed
filters: is:open repo:cli/cli
- title: Subscribed
filters: is:closed repo:cli/cli
```

Config change: put sections under the prSections key

---

config/parser.go
ui/model.go
ui/sidebar.go
ui/styles.go
ui/ui.go
ui/viewport.go

New config:
```yaml
prSections:
- title: My Pull Requests
filters: is:open author:@me
- title: Needs My Review
filters: is:open review-requested:@me
- title: Subscribed
filters: is:open -author:@me repo:cli/cli repo:dlvhdr/gh-prs`
defaults:
preview:
open: true
width: 50
```

Add defaults section to config: settings for preview

---

data/api.go
ui/sidebar.go

Show the head branch and the base branch in the sidebar

---

data/api.go
ui/markdown/markdownRenderer.go
ui/markdown/theme.go
ui/modelUtils.go
ui/section.go
ui/sidebar.go
ui/styles.go
ui/tabs.go
ui/ui.go
ui/viewport.go
utils/keys.go

- Added comments section to the sidebar
- Made the sidebar be rendered in a viewport
- Make ctrl+d, ctrl+u affect the sidebar
- comments mvp - need to refactor markdown to own file
- markdown styles
- make sidebar use pager

Comments in sidebar

---

data/api.go
ui/activity.go
ui/checks.go
ui/markdown/theme.go
ui/section.go
ui/sidebar.go

Show reviews under checks and comments

---

config/parser.go

remove backtick from config template

---

ui/mainViewport.go
ui/pr.go
ui/section.go
ui/styles.go
ui/ui.go
ui/viewport.go

Scroll main viewport when at edges

---

config/parser.go
data/api.go
ui/mainViewport.go
ui/model.go
ui/modelUtils.go
ui/section.go
ui/sidebar.go
ui/styles.go
ui/ui.go

New config:
```yaml
prSections:
- title: My Pull Requests
filters: is:open author:@me
- title: Needs My Review
filters: is:open review-requested:@me
limit: 5
defaults:
preview:
open: true
width: 60
prsLimit: 40
```
Closes #66

Configurable limit

---

CONTRIBUTING.md
gh-prs.go
ui/model.go
ui/ui.go

* Don't pass around the logger in the main model
* Use the global standard logger in the `log` package
* Add instructions to CONTRIBUTING.md

Use logger by calling the builtin log function

---

utils/utils.go

This PR adds support for multiple providers on linux to open the browser and also for users using WSL. (I use WSL)
https://user-images.githubusercontent.com/48808846/154288664-3dfbc7c0-52eb-4b89-8669-45d1be59b8e0.mp4
https://user-images.githubusercontent.com/48808846/154288730-ef3b97a9-9dd7-429e-bbdb-7783bc39367a.mp4

Support multiple providers to open browser on linux

---

ui/components/prssection/styles.go

fix ci column width

---

config/parser.go
data/issueapi.go
data/prapi.go
data/utils.go
ui/components/issue/issue.go
ui/components/issue/styles.go
ui/components/issuessection/issuessection.go
ui/components/issuessection/styles.go
ui/components/pr/pr.go
ui/components/prsidebar/activity.go
ui/components/prsidebar/prsidebar.go
ui/components/section/section.go
ui/components/section/styles.go
ui/components/table/table.go
ui/components/tabs/styles.go
ui/components/tabs/tabs.go
ui/context/context.go
ui/markdown/theme.go
ui/modelUtils.go
ui/ui.go
utils/keys.go

Implemented support for issues.
- Added config support for defining issue sections
- Added keybinding for switching between issues and PRs (`s`)
- Added current view (issues or prs) indicator in the top right corner
- The view's sections are only fetched when it is first viewed
- Modularize code and reused for issues
- Small fixes
TODO:
[] Ability to specify CLI param that indicates the view to start with
[] Sidebar support for issues
Manually

Support for Issues

---

ui/components/issuessection/issuessection.go
ui/components/listviewport/listviewport.go
ui/components/prssection/prssection.go
ui/components/section/section.go
ui/components/table/table.go
ui/constants/constants.go
ui/ui.go
utils/keys.go

Fixes #104.
I tested this issue by thinking about corner cases and trying them out.
Please ignore the weird quality

feat(keys): implements first/last line navigation

---

data/prapi.go
go.mod
go.sum
ui/components/help/help.go
ui/components/help/styles.go
ui/components/issuessection/issuessection.go
ui/components/issuessection/styles.go
ui/components/pr/pr.go
ui/components/prssection/prssection.go
ui/components/prssection/styles.go
ui/components/search/search.go
ui/components/section/section.go
ui/components/section/styles.go
ui/components/sidebar/sidebar.go
ui/components/table/styles.go
ui/components/table/table.go
ui/components/tabs/styles.go
ui/components/tabs/tabs.go
ui/context/context.go
ui/modelUtils.go
ui/styles/styles.go
ui/ui.go
utils/keys.go

search component + integrating into existing sections

---

data/prapi.go
gh-dash.go
ui/markdown/markdownRenderer.go
ui/styles/theme.go

theme-fixes

---

data/user.go
go.mod
go.sum
ui/components/prsidebar/comment.go
ui/components/prsidebar/prsidebar.go
ui/components/prssection/checkout.go
ui/components/prssection/close.go
ui/components/prssection/cmds.go
ui/components/prssection/diff.go
ui/components/prssection/prssection.go
ui/components/sidebar/sidebar.go
ui/constants/progressMsg.go
ui/context/context.go
ui/keys/prKeys.go
ui/modelUtils.go
ui/ui.go

- fix(help): add checkout to help pane
- feat(prs): close command
- feat(pr): comment command
- fix: prevent submission of empty comments

feat(prs): comments

---

ui/components/prssection/prssection.go
ui/components/prssection/ready.go
ui/components/prssection/reopen.go
ui/constants/initMsg.go
ui/keys/prKeys.go

- refactor: make InitMsg public so all components can listen to it
- feat(prs): add ready for review command
- feat(prs): reopen pr command

More PR commands

---

ui/components/prssection/merge.go
ui/components/prssection/prssection.go
ui/keys/prKeys.go
ui/ui.go

merge PR command

---

go.mod
go.sum

- fix: go mod tidy
- chore: upgrade to go 1.18

upgrade go 1 18

---

.github/workflows/go-release.yml

fix(action): github action - upgrade to 1.18

---

ui/ui.go

Change the default view to `issues`, then verify that the preview has been updated. 

fix(ui): preview unrenewed when default view is `issues`

---

ui/components/commentbox/commentbox.go
ui/components/issuesidebar/issuesidebar.go
ui/components/prsidebar/prsidebar.go
ui/styles/styles.go

fix(sidebar): set height on comment box

---

cmd/root.go
config/parser.go
gh-dash.go
ui/context/context.go
ui/styles/theme.go
ui/ui.go

feat(config): support custom config file flag

---

go.mod
go.sum

fix(deps): get cobra

---

ui/components/commentbox/commentbox.go
ui/components/help/help.go
ui/components/issuesidebar/issuesidebar.go
ui/components/issuessection/issuessection.go
ui/components/listviewport/listviewport.go
ui/components/prsidebar/prsidebar.go
ui/components/prssection/prssection.go
ui/components/section/section.go
ui/components/table/table.go
ui/context/styles.go
ui/ui.go

feat(ui): show last updated time of section

---

ui/keys/keys.go
ui/ui.go

feat(keys): add keybinding to refresh all sections

---

config/parser.go
ui/components/section/section.go
ui/ui.go

feat: add ability to refresh all sections at an interval

---

config/parser.go
ui/components/section/section.go
ui/ui.go

fix(refresh): don't fetch username on refresh all

---

cmd/root.go

feat(cmd): add version flag

---

data/prapi.go
ui/components/issuessection/issuessection.go
ui/components/listviewport/listviewport.go
ui/components/prssection/prssection.go
ui/components/section/section.go
ui/components/table/table.go
ui/context/context.go
ui/ui.go

fix: prevent fetch of next page on refresh

---

data/issueapi.go
ui/components/issuessection/issuessection.go

feat(issues): add pagination

---

ui/components/prssection/prssection.go

fix: remove log

---

.goreleaser.yaml

fix(release): remove proxy

---

.goreleaser.yaml

Fix goreleaser for gh

---

cmd/root.go
data/issueapi.go
data/prapi.go
go.mod
go.sum
ui/context/context.go
ui/modelUtils.go
ui/ui.go
utils/utils.go

feat(logging): use charmbracelet/log for debug logging

---

.github/workflows/hugo.yaml

docs: set up hugo github action

---

.github/workflows/hugo.yaml

fix: hugo workflow

---

docs/data/schemas/layout/pr.yaml
ui/constants/constants.go

Fix missing nerd fonts using nerdfix

Fix missing/obsolete nerd font glyphs

---

.github/workflows/go-release.yml

ci: upgrade github actions

---

ui/modelUtils.go
ui/ui.go

fix: copy to clipboard notification

---

ui/components/footer/footer.go

Fixes #337
- **update footer to include username**
Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>

update footer to include username

---

README.md
config/parser.go
ui/components/footer/footer.go
ui/ui.go

This PR addresses #355.
Show prompt on quit. Also, add `confirmQuit` to the configuration file to change whether it shows the prompt.
I manually tested this change following the procedures shown in the video below. I confirmed that it shows the prompt when I set `confirmQuit=true` on the configuration and vice versa.
https://github.com/ushmz/gh-dash/assets/44394399/0ba059e2-341c-4fee-a99c-431cfcb781fe

Add prompt for confirmation on quit

---

ui/components/footer/footer.go

ui: better display for username in footer

---

.github/workflows/go-release.yml
.goreleaser.yaml

chore: upgrade goreleaser

---

.github/workflows/go-release.yml
.goreleaser.yaml

- **chore: upgrade goreleaser**
- **fix: goreleaser duplicate artifacte names due to goarm**

fix: goreleaser duplicate artifacte names due to goarm

---

README.md
config/parser.go
docs/data/schemas/theme.yaml
ui/components/issuessection/issuessection.go
ui/components/prssection/prssection.go
ui/components/section/section.go
ui/components/table/table.go
ui/components/tabs/tabs.go
ui/context/context.go
ui/ui.go
utils/utils.go

feat: support showing the number of results in the tab bar

---

README.md
ui/components/prsidebar/approve.go
ui/components/prsidebar/prsidebar.go
ui/keys/prKeys.go
ui/ui.go

Adds the option to approve a PR, this is handy when working in a team and with having some branch protections in place (like require X approvals to merge).
`go run ./gh-dash.go --debug`

feat(approve): Add PR approval cmd

---

ui/common/styles.go

fix: help height

---

ui/components/prsidebar/approve.go

chore: remove unnecessary if statement

---

ui/components/tasks/pr.go

fix: merge pr

---

ui/components/reposection/commands.go
ui/components/reposection/reposection.go
ui/components/section/section.go
ui/components/tasks/pr.go
ui/keys/branchKeys.go
ui/ui.go

- **feat(branches): force push**
- **feat(branches): create pr**

feat(branches): create pr

---

ui/components/branch/branch.go
ui/components/branch/data.go
ui/components/branchsidebar/branchsidebar.go
ui/components/reposection/reposection.go
ui/ui.go

feat(branches): sidebar skeleton

---

ui/components/issuessection/issuessection.go
ui/components/prssection/prssection.go
ui/components/reposection/reposection.go
ui/components/section/section.go
ui/ui.go

feat: dont show full screen loading on interval refetch

---

ui/components/issuessection/issuessection.go
ui/components/prssection/prssection.go
ui/components/reposection/reposection.go

fix: attempt to fix memory leak

---

.gh-dash.yml
README.md
cmd/root.go
config/parser.go
docs/content/getting-started/usage.md
git/git.go
ui/ui.go

feat: read .gh-dash.yml file in repo root if exists

---

config/feature_flags.go
data/prapi.go
imposters/config.yml
imposters/gh-dash.yml
imposters/pr.imp.json
imposters/pr.json
ui/components/prsidebar/prsidebar.go

fixes #491 
I have no idea why, but [this line](https://github.com/dlvhdr/gh-dash/blob/dlvhdr/mock-server/ui/components/prsidebar/prsidebar.go?plain=1#L323) solves it.

fix: memory leak

---

cmd/root.go
config/parser.go
ui/components/branchsidebar/branchsidebar.go
ui/components/footer/footer.go
ui/components/issuesidebar/issuesidebar.go
ui/components/issuessection/issuessection.go
ui/components/prsidebar/prsidebar.go
ui/components/prssection/prssection.go
ui/components/reposection/commands.go
ui/components/reposection/reposection.go
ui/components/search/search.go
ui/components/section/section.go
ui/components/sidebar/sidebar.go
ui/components/tabs/tabs.go
ui/components/tasks/pr.go
ui/context/context.go
ui/ui.go

(may or not be fully working)
you need to undo the 50ms if you were to merge this

better fix for leak and cleanup of unnecessary string ptr

---

ui/components/branch/branch.go
ui/components/prssection/prssection.go
ui/components/reposection/commands.go
ui/components/reposection/reposection.go
ui/components/tasks/pr.go

Fix typos found via `typos --hidden --format brief`
```
go run gh-dash.go --debug
```

docs: fix typos

---

ui/components/footer/footer.go
ui/components/tabs/tabs.go
ui/context/context.go
ui/context/styles.go
ui/ui.go

feat: better footer + show version

---

data/prapi.go
ui/common/styles.go
ui/components/pr/pr.go
ui/constants/constants.go

feat(prs): show comments review status

---

Makefile
flake.nix
ui/components/footer/footer.go

fix: nerd font icon

---

Makefile
docs/default.nix
flake.nix

build(docs): nix + makefile

---

docs/content/getting-started/usage.md

Trivial documentation update because I fell for the trap. Thanks for the great tool! 
N/A
N/A

docs: update usage.md with correct $XDG_CONFIG_HOME path

---

ui/constants/constants.go

chore: update colab icons

---

ui/common/styles.go
ui/components/prsidebar/checks.go

feat: show merge status in bigger state

---

ui/components/prsidebar/prsidebar.go

chore: remove pills and move to status to top

---

ui/components/prsidebar/checks.go

feat: add closed state

---

imposters/pr.json
ui/common/labels.go
ui/components/issuesidebar/issuesidebar.go
ui/components/prsidebar/prsidebar.go
ui/context/styles.go
ui/markdown/theme.go

feat: improve labels in pr sidebar

---

Makefile
flake.lock
flake.nix

build: nix

---

imposters/pr.json
ui/components/prsidebar/files.go

fix: long file names

---

.gh-dash.yml
docs/data/schemas/keybindings/entry.yaml

docs: custom command names

---

ui/components/issuessection/issuessection.go
ui/components/prssection/prssection.go
ui/components/reposection/reposection.go
ui/components/section/section.go
ui/components/tabs/tabs.go
ui/ui.go

feat: show loading indicator in tab name

---

README.md

Fix glamour link in README.md

---

.gh-dash.yml

chore: local .gh-dash.yml to  merge as admin

---

.gh-dash.yml
docs/data/schemas/keybindings/entry.yaml
imposters/pr.json
ui/components/issuesidebar/issuesidebar.go
ui/components/prsidebar/prsidebar.go
ui/components/sidebar/sidebar.go
ui/context/styles.go
ui/keys/prKeys.go
ui/ui.go

feat(pr-sidebar): summary view more

---

ui/components/pr/pr.go
ui/components/prsidebar/files.go
ui/components/prsidebar/prsidebar.go

feat(pr-sidebar): changes summary

---

imposters/pr.json
ui/components/prsidebar/checks.go
ui/components/prsidebar/files.go

fix(pr-sidebar): allow long file names

---

imposters/pr.imp.json
ui/ui.go

fix(prs): remove shown pr in sidebar when refreshing

---

cmd/root.go
ui/components/section/section.go
ui/ui.go
utils/templateHandler.go

Possible fix for #600.
It's hard to tell if this really fixes the issue, since it's hard to reproduce.

fix: intermittent crash

---

docs/src/styles/custom.css

fix(docs): css

---

docs/src/pages/index.astro

fix(docs): charm name

---

devbox.json
go.mod

build: fix devbox go install

---

cmd/root.go
config/parser.go
config/parser_test.go
config/testdata/.gh-dash.yml
config/testdata/other-test-config.yml
config/testdata/test-config.yml
ui/context/context.go
ui/ui.go

test: config file parser basic test

---

docs/src/components/PillLink.astro
docs/src/styles/custom.css
docs/src/styles/index.css

docs: fix header (#639)

---

.goreleaser.yaml

build(goreleaser): better templates

---

docs/src/content/docs/insiders/enhance/getting-started.mdx

docs: fix insiders link

---

.gh-dash.yml
internal/tui/components/issuesidebar/issuesidebar.go
internal/tui/components/issuesidebar/label.go
internal/tui/components/issuessection/issuessection.go
internal/tui/components/prsidebar/prsidebar.go
internal/tui/keys/issueKeys.go
internal/tui/ui.go

feat(issues): edit labels

---

.goreleaser.yaml

chore: fix footer in goreleaser

---

docs/src/components/SponsorshipGoal.astro

docs: limit fraction digits to 2
