dlvhdr/gh-dash

ui/modelUtils.go, ui/pr.go, ui/section.go, ui/styles.go, utils/utils.go
Removes dead code flagged by `golangci-lint`
A mix of styles from the example provided by lipgloss and several utility functions are not used within the codebase.
=> removes dead code from ui and utils

README.md
adds clarifications to the README following first time setup of the extension:
* specify a minimum `gh` cli version e.g. v2.0.0 is when extensions were introduced. 
* adds notes on `sections.yml` configuration location being provided in a prompt when running `gh prs`.
* fixes formatting, grammar, and typos in README
=> adds clarifications to README to specify minimum gh version

gh-prs.go
By passing --debug, the file will be created.
Otherwise, it won't and no debugging will be possible.
=> add option to not create the debug.log file

release.sh
There was a bug in the release script that didn't publish the darwin-amd64 exe
=> Support darwin-amd64

release.sh
Add FreeBSD builds to the release process (free with Go's cross compilation).
=> ci: add FreeBSD builds

ui/components/pr/pr.go, ui/components/prsidebar/checks.go, ui/components/prsidebar/prsidebar.go
Pending checks that are defined in the `StatusContext` were not properly rendering as pending.  Check runs worked fine, but external CI services like Buildkite which use `StatusContext` were not rendering properly.
I also improved the formatting of the pending checks pill which was rendering strangely before.
Verified that pending checks work properly after this change.
=> Fix pending checks not always rendering as pending

README.md, go.mod, go.sum, ui/modelUtils.go
Adds support for use of repository and path wildcards in `config:repoPaths` to permit:
- owner/* repo matching to common local path (path-segment/*)
- match `owner/*` to `path-segment/repo`
- prioritize full repo ( `owner/repo: ~/somePath/target`) when present
- executes only when invoking `runCustomCommand`
Avoids having to individually add each repo-path combination for org/owner while retaining no-match/no-mapping behavior and prioritizing direct-mapped owner/repo to full path.
Assumes repo wildcard match is defined as `owner/*` and that path is well-formed partial path, ending with `/*`
First `go` attempt - chose simple `strings` manipulation over `regexp` given the limited matching cases of owner/repo, owner/\*, path/.../\*. Also chose to introduce `getRepoLocalPath` in modelUtils.go …
=> repo/path wildcard matching - closes #151

ui/components/pr/pr.go, ui/components/prsidebar/prsidebar.go
Tweak a couple of key bits of the UI to differentiate an open draft PR from an open non-draft PR in the table view and the sidebar.
I decided to scope this change to only affect _open_ draft PRs.  A closed PR could also be a draft, but that seems much less useful and important once it's been closed.
Fixes #157
I ran it locally with my config which currently contains a draft PR.
**Before**
**After**
=> Differentiate draft PRs from open PRs

config/parser.go
This changes the `Subscribed` tabs in the default config to `Involved`
tabs and changes the filter from hard-coded repos (such as `cli/cli`) to
`involves:@me`.
This addresses behavior that has surprised some folks such as in #74 and #129.
Ideally, we could fetch issues/PRs that the user has subscribed to, but
it looks like there's not an obvious way to do that. In its absence, the
`involves` filter might be a reasonable default that is less surprising
to people.
I changed my local config to match this and ran `gh dash` to observe the results.
Admittedly I did not set up a `go` environment to test these changes.
=> Change default Subscribed tab to Involved

ui/keys/keys.go
Add back "open in GitHub" to the help.
I ran it locally and toggled the help screen.
Before:
After:
=> Add "open in Github" to the help

.github/workflows/test.yml, data/prapi.go, ui/components/prssection/pressection_test.go, ui/components/prssection/prssection.go
I have seen this issue. I added a change to exclude PRs in archived repositories.
https://github.com/dlvhdr/gh-dash/issues/124
I would have liked to be able to remove PRs from archived repositories in the Github API arguments, but after checking the documentation I found it difficult to do so. I have added an implementation to remove pull requests from archived repositories after fetching pull requests.
I wrote unit tests for the added functions.
I ran the command `gh dash` to see if it was successful in removing pull requests from archived repositories.
I used this archived repository.
https://github.com/yokishava/k8s-manifest-ci-demo
=> fix: #124 exclude pull requests of archived repositories

ui/components/issue/issue.go, ui/components/issuesidebar/issuesidebar.go, ui/components/pr/pr.go, ui/components/prsidebar/prsidebar.go, utils/utils.go
Removes truncation on repo name and adds full name + number to the sidebar. See #217 .
Manually, with a repo name longer than the default of 18 characters.
=> Remove truncation of repo name.

config/parser.go, data/assignee.go, data/issueapi.go, data/prapi.go, ui/components/pr/pr.go, ui/components/prssection/prssection.go
This PR adds the `assignees` field to PRs. It is essentially identical to what already exists for issues. The default configuration is for this field to be rendered (i.e. `hidden: false`) - as is the case for issues - and the length is `20` - again, the same as for issues.
I (and others on my team) use the assignment feature to keep track of PRs that we are responsible for, independent of who created the PR. It is helpful for us to see which PRs are unassigned or assigned to others.
I tested this change by configuring the dashboard to look at repositories with a mixture of assigned and unassigned PRs. See screenshot below.
=> Add assignees to PRs.

README.md, config/parser.go, ui/modelUtils.go, ui/ui.go
This PR adds support for custom keybindings for issues. This is essentially identical to what already exists for PRs. I personally leverage this feature quite a lot, and it will also make it easy to iterate on any potential future built-in commands for issues, as we can prototype them first via this mechanism.
There are a few areas where the de-duplication between issues and PRs could have achieved in multiple different ways. For example, one could leverage generics, but I felt the overhead wasn't worth the minor reduction in code.
If you want to refactor things a different way - no problem. Just let me know
I added the example issue keybinding from the readme and validated that it worked as expected.
None - because the lack of feedback when running custom commands makes it hard to …
=> Add support for custom keybindings on issues

README.md, config/parser.go, ui/components/pr/pr.go, ui/components/prssection/prssection.go
This PR adds the base branch to the list of data present in the PRs list.
I tested locally to validate that the `Base` column is present only when the column is unhidden in the config.
=> feat(prs): adds base branch to pr columns

ui/common/repopath.go, ui/common/repopath_test.go, ui/components/prssection/checkout.go, ui/modelUtils.go
This PR adds support for using wildcard paths for repo lookup for built-in commands in addition to the existing support for custom commands. Currently only custom commands support wildcard lookups for repo paths.
I had to refactor the existing code into a third package to avoid an import loop.
Additionally, as part of this refactor, I was able to improve the error handling for custom commands when the repo lookup failed.
Finally, I added unit tests for the wildcard matching, as I felt it was the easiest way to track the behavior of this function. I used vanilla golang testing - I did not add any additional libraries.
Fixes #250 
I confirmed that this change allows wildcard matching for built-in commands via manual testing. I used the `C`/`checkout` command as that interacts with the file …
=> Wildcard matching builtin

go.mod, go.sum, ui/ui.go, utils/utils.go
Change to use the same browser opening code that the `gh` CLI uses as opposed to a custom implementation in order to make things act like they would for things like opening the `gh auth login` command.
Opened a PR with this change as seen under the images/videos on my mac
https://user-images.githubusercontent.com/839261/235380595-f33ea68c-0e49-4a0f-b705-1c1eb8ec6837.mov
=> chore: use gh native browser launch code

.github/workflows/hugo.yaml, docs/go.mod, docs/go.sum, docs/hugo.yaml
Prior to this change, the docs site could not build in GHA because it was being built for a base URL that is in a folder after the top-level domain name. This change updates the Hugo module dependencies now that a fix for this bug was merged upstream for the schematize module.
This change also corrects the module declaration for `gh-dash`, which should not have any effect as the module is replaced with the local reference in the configuration, but might as well be technically correct.
Finally, this change updates the GHA for building the site, removing the `-u` flag from the module install, which updates the modules. This way, dependency updates can be intentional and the `go.mod` / `go.sum` files in the repository are the sources of truth.
Local build/serve with the updated URL, ensured …
=> (MAINT) Update docs site dependencies & build

.goreleaser.yaml
This adds support for 32 bit arm as well as android arm64 to fix #266.  This is definitely a niche change, and while I did try to take care of #249 at the same time, I ran into android specific compilation errors so abandoned that change.
I only tested the build procedure, not the actual running software due to lack of hardware.
=> linux arm v6 and v7 compilation

docs/data/_params/platen.yaml, docs/go.mod, docs/go.sum, docs/hugo.yaml
This change updates the configuration and version of the docs theme to the latest version of Platen and opts-into the new display modes.
This update includes a fix to a build error caused by the Platen reimplementing the TOC building logic and ensures that the docs site builds correctly without errors or warnings.
The new opt-in features gets the docs site ahead of the eventual deprecation and removal of legacy functionality and keeps the build logs clean. It also ensures:
1. The site can more effectively use icons.
1. The TOC nodes with nested items can be collapsed.
1. The mobile buttons are more usable and accessible.
1. The site-level icons are configurable and can be kept cohesive.
Finally, the change moves the remaining Platen configuration out of the `hugo.yaml` file, colocating it …
=> (MAINT) Update docs theme

README.md, cmd/root.go, config/parser.go, docs/content/configuration/_index.md, docs/content/getting-started/usage.md
This PR adds functionality to specify a location for the configuration file using an environmental variable (`$GH_DASH_CONFIG`). Users can specify a default path for the config file outside of `$XDG_CONFIG_HOME/gh-dash/config.yml`.
Additionally, it refactors getExistingConfigFile and getDefaultConfigFileOrCreateIfMissing, and updates the documentation. 
* reads and generates configuration files in the default location when `$GH_DASH_CONFIG` is not set.
* reads and generates configuration files in location specified by `$GH_DASH_CONFIG` if `$GH_DASH_CONFIG` is set. If the directory does not exist, it creates it.
* accepts `--config` overrides.
N/A
=> add `$GH_DASH_CONFIG` environmental variable

ui/common/styles.go, ui/components/issuessection/issuessection.go, ui/components/prompt/prompt.go, ui/components/prssection/prssection.go, ui/components/section/section.go, ui/ui.go
Add prompt confirmation before closing a PR in #197
Add prompt confirmation before performing a gh action related to PRs and Issues as additional
- PR actions
- close
- reopen
- ready
- merge
- Issue action
- close
- reopen 
I tested this newly added feature manually for every PR and Issue action.
=> feat(ui): ability to prompt a confirmation before an action is performed

ui/components/pr/pr.go, ui/components/prssection/prssection.go, ui/components/utils.go
UI changes proposal on +/- with colors like the view we have on github.
On my Ubuntu Os 20.04 , tmux, under allacrity.
```bash
go run gh-dash.go --debug
```
- This should work for all Unix based system.
- I didn't create an issue because i thought there were not too many things to do on this branch, I hope it's okay.
=> feat(ui): update the PR view diff changes summary

README.md
When trying to manually install `gh-dash` I couldn't make it work, getting the error:
```
failed to run extension: fork/exec /Users/sebastiaramon/.local/share/gh/extensions/gh-dash/gh-dash: no such file or directory
```
After running `go build` I stopped getting the error above.
=> Add Go build step to README

data/issueapi.go, data/prapi.go, ui/components/issuesidebar/activity.go, ui/components/issuesidebar/comment.go, ui/components/issuessection/issuessection.go, ui/components/prsidebar/activity.go, ui/ui.go
- **feat(prs): show review threads in sidebar**
=> feat(prs): show review threads in sidebar

.goreleaser.yaml
includes project name in the release assets 
Fixes #335 
<details><summary>Details</summary>
<p>
```bash
goreleaser release --snapshot
• starting release...
• loading                                          path=.goreleaser.yaml
• skipping announce, publish and validate...
• loading environment variables
• getting and validating git state
• git state                                      commit=bf3764ced0f35251bc315e634366ea4582313e90 branch=main current_tag=v3.14.0 previous_tag=v3.13.1 dirty=true
• pipe skipped                                   reason=disabled during snapshot mode
• parsing tag
• setting defaults
• snapshotting
• building snapshot...                           version=3.14.1-next
• running before hooks
• running                                        hook=go mod tidy
• …
```
=> include project name in release assets

ui/ui.go
close #339
I've fixed the issue where resizing the window height while the help is displayed no longer disrupts the layout.
This is a fix for issue #339. 
Manually tested by resizing the terminal window with the help view open.
https://github.com/dlvhdr/gh-dash/assets/27483768/b119812c-080f-4c3a-9bcf-8707e177661d
=> fix layout disruption when resizing window with help displayed

README.md, ui/common/repopath.go, ui/common/repopath_test.go
Previously, we supported a "wildcard" mapping like
```yml
user1/*: /path/to/user1_repos/*
```
to map any repository owned by `user1` to the directory of the same name within `/path/to/user1_repos/`.
But for folks who store all GitHub repositories under a path that includes the owner's name and the repo's name, this would still require them to enter a wildcard entry for every owner. To avoid that, this PR introduces support for an `:owner/:repo` template in the `repoPaths` configuration. Now we can specify a `repoPaths` entry like:
```yml
:owner/:repo: /path/to/github.com/:owner/:repo
```
which will cover everything. It can still be overridden with individual entries that specify either an exact repository or a specific owner wildcard.
I added more test cases to …
=> Support `:owner/:repo` template in repoPaths configuration

README.md, ui/common/repopath.go, ui/common/repopath_test.go
Now that we support the more general `:owner/:repo` template configuration (https://github.com/dlvhdr/gh-dash/pull/343), the prior `default_path` functionality (https://github.com/dlvhdr/gh-dash/pull/327) is redundant - e.g. this configuration:
```yml
default_path: ~/code/repos
```
can be achieved equivalently with:
```yml
:owner/:repo: ~/code/repos/:repo
```
Thus, we are removing the `default_path` syntax.
I updated the automated tests to show how the `default_path` test case is covered with the `:owner/:repo` syntax.
=> Remove `default_path` support in `repoPaths` configuration

README.md, ui/modelUtils.go
closes #346
I could successfully use `BaseRefName` in the config to view the PRs' diff in neovim for different PRs with different base branches in the same repository.
=> Allow BaseRefName in template

data/prapi.go
=> fix: queries exceeding number of allowed nodes

config/parser.go, docs/data/schemas/defaults.yaml, ui/components/issue/issue.go, ui/components/pr/pr.go
Currently only affects the updated at field for PRs and issues.
Hoping to get feedback on this idea and help contribute to documentation or schema update as required.
Closes #67
This config will use a simple yyyy-mm-dd format with a larger column layout. Not entirely sure why its 12 width and not 10, maybe there is some padding by default.
```yaml
defaults:
layout:
prs:
updatedAt:
width: 12
grow: true
dateFormat: "2006-01-02"
```
The special value of RELATIVE, or no value at all, will keep the existing relative dates.
```yaml
defaults:
dateFormat: "relative"
```
With format `2006-01-02`
=> Add date format option to defaults

ui/components/issuessection/issuessection.go, ui/components/prssection/prssection.go, ui/components/section/section.go
This PR addresses https://github.com/dlvhdr/gh-dash/issues/294
I have implemented a modification to retain the TaskID for each fetch task within the model. This TaskID is identical to the one included in the msg sent upon the completion of a record fetch. Saving taskID within the model is a Last-Write-Wins basis, ensuring that only the most recent TaskID is stored in the model.
The PR and issue lists within the model are updated only if the TaskID in the model matches the TaskID in the incoming message. 
I manually tested this change following the procedures shown in the video below. I confirmed that the issue was resolved without negatively impacting other functionalities such as paging or searching.
https://github.com/dlvhdr/gh-dash/assets/27483768/a78eb21e-f217-4771-8865-d3f2a76a32d6
=> fix: duplicate record display on rapid consecutive refreshes

ui/modelUtils.go
Moved common functionality from `runCustomPRCommand()` & `runCustomIssueCommand()` into new `runCustomCommand()` function
Set and ran rudimentary custom commands in each context. Could probably do with some more robust testing though tbh.
I've left an empty `input` map still initialised in the new function, and merged in the specific data from the calls from different contexts, as I'm not sure what common data might want to be made available common to different contexts.
=> Streamline custom commands

ui/keys/issueKeys.go, ui/keys/keys.go, ui/keys/prKeys.go, ui/ui.go
It was hard for me to find the capability to view issues -- I saw it mentioned in the README, but I couldn't find it in the `?` menu. This PR proposes varying the help text for the "switch view" action so that the words "issues" or "PRs" are present where applicable.
E.g.:
```
...
s Switch to issues
```
or
```
s Switch to PRs
```
Alternatively, we could use the simpler
```
s View issues
```
but that would lose the nice acronym. Also, "switch" feels like a relevant hint that this will fully replace the current view.
```sh
go run .
```
=> Use "Switch to issues" and "Switch to PRs" for better observability

ui/common/labels.go, ui/common/labels_test.go, ui/components/issuesidebar/issuesidebar.go, ui/components/prsidebar/prsidebar.go
Fixes an issue where labels did not wrap neatly when their total length was longer than one line. (see https://github.com/dlvhdr/gh-dash/pull/369#issuecomment-2132224396). The previous behavior was inconsistent - sometimes it would wrap the label color but not the label text; sometimes it would fail to render labels at all.
I also backported the same logic to the issue sidebar, as it was already present there but we just hadn't discovered it yet.
With a PR (and issue) that had multiple labels associated with them
This is the new behavior. Notice the clean wrapping across multiple lines
The code is fairly clunky as it is manually building the multiple rows that consist of multiple lables. I couldn't find a native way to do this in the UI library (`lipgloss`). If there's a cleaner way to …
=> Render labels cleanly across multiple lines.

ui/components/issuessection/issuessection.go, ui/components/prssection/prssection.go, ui/components/section/section.go, ui/components/table/table.go
Resolves #363 
This is my first PR to gh-dash. So if I'm doing something wrong. Please let me know that. 😅
Show `Loading...` when gh-dash fetching PRs(not issues because the Tip is showed when issues are being fetched currently)
Verify `Loading...` is showed when:
- gh-dash is launched
- `r` key is pushed
- `R` key is pushed
https://github.com/dlvhdr/gh-dash/assets/49891479/24584df0-9a6b-4444-a325-f0bec1550456
https://github.com/dlvhdr/gh-dash/assets/49891479/e2896a10-0440-4f1e-b156-fd64b4072433
I considered to showing `Loading...` on sidebar too. But the message currently showed is suitable too. So I did not change it.
=> feat: showing a loading message

config/parser.go, docs/data/schemas/theme.yaml, ui/components/issue/issue.go, ui/components/issuessection/issuessection.go, ui/components/pr/pr.go, ui/components/prssection/prssection.go, ui/components/table/table.go, ui/components/utils.go, ui/constants/constants.go, ui/context/styles.go, utils/utils.go
=> Support sparse layout in tables

Makefile
I added `Makefile`.
This is useful for the person who is new to this repository like me because the commands commonly used tell us how to develop.
If some commands fall off from `Makefile` please let me know.
=> chore: add `Makefile`

ui/components/prsidebar/prsidebar.go
This is a follow-up to https://github.com/dlvhdr/gh-dash/pull/399 to address https://github.com/dlvhdr/gh-dash/pull/399#pullrequestreview-2239389841
That PR added support for approving PRs. However, the code was requiring that a comment be entered, or else the approval wouldn't occur. This seemed unintended because the implementation of the `approve` method had some code to explicitly handle the case where the comment was empty:
https://github.com/dlvhdr/gh-dash/blob/d9033f7855730e536f5a3ecfbd8cb8e9f4c9268b/ui/components/prsidebar/approve.go#L33-L35
It was likely just a copy-paste mistake - the code for leaving a regular comment was aborting if the comment was empty (or only whitespace), which makes sense (but doesn't apply for approvals).
I built this branch locally and ran it and used …
=> Enable approving a PR without entering a comment

README.md, config/parser.go, data/prapi.go, ui/components/pr/pr.go, ui/components/prsidebar/prsidebar.go, ui/components/prssection/prssection.go, ui/components/reposection/reposection.go, ui/components/section/section.go, ui/components/tasks/pr.go, ui/constants/constants.go, ui/keys/branchKeys.go, ui/keys/prKeys.go, ui/theme/theme.go, ui/ui.go
Added `-u` to update a PR from a base branch
Added a mergeStateStatuspill
Added a error theme colour
Changed warning colour to yellow from red
1. built repo locally
2. ran with `--debug`
3. verified via debug that it was calling the function
```
8:56AM DEBU <ui/ui.go:163> Key pressed key=u
8:56AM DEBU <ui/ui.go:163> Key pressed key=y
8:56AM DEBU <ui/ui.go:163> Key pressed key=enter
8:56AM DEBU <tasks/pr.go:244> Updating PR prNumber=xxx
8:56AM DEBU <ui/ui.go:69> Starting task id=pr_update_xxx
8:56AM DEBU <tasks/pr.go:62> Running task cmd="gh pr update-branch xxx -R xxx/xxx"
8:56AM DEBU <ui/ui.go:505> Task finished id=pr_update_xxx
```
4. verified PR in the UI was also updated
5. verified the Pills in the UI changed as they are updated
=> Feat: added '-u` to update PR from base branch

README.md
With the additional property of `error` added to theme color in the
dlvhdr/gh-dash#458, the configuration of themes break if this property is
missing. This patch then adds it to the example to help users understand what's
required for theming `gh-dash`.
If the `~/.config/gh-dash/config.yml` contains a reference to a `theme:colors`
stanza but the `text` stanza doesn't contain an `error` property, you will see
the following error.
```sh
2024-10-30T12:24:29-05:00 FATA <ui/ui.go:107> Reading config file: failed parsing config file location="" err="failed parsing config.yml: Key: 'Config.theme.colors.Inline.text.error' Error:Field validation for 'error' failed on the 'hexcolor' tag"
```
And it breaks the rest of your shell session as well. It's probably a good idea
to fix that error with some …
=> docs: Adding error property to theme example;

ui/components/search/search.go
When the `filters` are too long, the TextInput wraps into a new line with a visual artifact.
This might be an issue with BubbleTea itself, but let me know if I should try to fix it here or in BubbleTea.
I reused the same values as `getInputWidth`.
> Note: This is my first Go and BubbleTea contribution 🎉 
I reproduce the issue locally with the following settings:
```yml
prSections:
- title: Very long PR filter
filters: is:open very very very very very very very very very very very very very very very very very long review:required sort:created-asc
issuesSections:
- title: Very long Issue filter
filters: is:open very very very very very very very very very very very very very very very very very long review:required sort:created-asc
```
I tested the changes with both focusing on the search …
=> fix: initial textinput size

ui/ui.go
This addresses #475
I get a runtime error: invalid memory address or nil pointer dereference on launching gh dash when the version is >= 4.6.0.
1. `gh extension install dlvhdr/gh-dash`
2. `gh dash` 
3. See stack trace in #475
4. Remove extension
5. `gh extension install dlvhdr/gh-dash --pin v4.5.4`
6. `gh dash`
7. No crash
8. Remove extension
9. `gh extension install dlvhdr/gh-dash --pin v4.6.0`
10. Crash with stack trace equivalent to the one in #475 
11. `git clone` gh-dash
12. Apply this change
13. `go build` && `go install .`
14. `gh dash`
15. No crash ✅
=> Fix nil pointer deref introduced in 4.6.0 by introducing guard around potentially `nil` currSection

.github/workflows/hugo.yaml
In CI there was a lot of deprecation warnings, a bump for each of the deprecated actions should fix it for now.
TLDR of the major bumps
- [actions/checkout](https://github.com/actions/checkout/releases/tag/v4.0.0): Node 20
- [actions/configure-pages](https://github.com/actions/configure-pages/releases): Node 20 and Next.js relating things
- [actions/upload-pages-artifact](https://github.com/actions/upload-pages-artifact/releases): New Github Artifacts API
- [actions/deploy-pages](https://github.com/actions/deploy-pages/releases): Uses  `actions/upload-pages-artifact` v3 or newer
With the new Github Artifacts API, the page URL is not needed anymore and retrieved through the Artifact id.
Tested it on my fork [here](https://github.com/alcpereira/gh-dash/actions/runs/11714252937)
=> ci: bump actions to latest versions

.github/workflows/hugo.yaml, CONTRIBUTING.md, docs/go.mod, docs/go.sum
While working on #471 I had some difficulties running the docs server due to an old version of Hugo.
I this PR I bumped it to the latest compatible version with platen ([commit](https://github.com/platenio/platen/pull/102/commits/a0d17cff85da2e97ed0df8fb9484a1a6b98bc4d9)). This version issue was noticeable in the CI logs ([here](https://github.com/dlvhdr/gh-dash/actions/workflows/hugo.yaml)).
It works on my machine™
=> docs: bump hugo and add instruction on how to run docs server locally

docs/content/getting-started/keybindings/selected-pr.md
The docs were incorrectly mapping `w` as the Ready for review shortcut. The correct one is `W` (uppercase).
Haven't succeed yet to build the docs locally, should we update to the latest Hugo version? And also the `CONTRIBUTING.md` on how to build the docs.
=> docs: fix ready for review shortcut W instead of w

.goreleaser.yaml
Should fix #249, #304 and #468  🤞 
I also added in this PR two small fixes:
- YAML formatting due to the `schema.json` was complaining about `goarm` being a list of integer and not strings
- A deprecation notice regarding [snapshot.name_template](https://goreleaser.com/deprecations/#snapshotname_template)
I cannot properly test it due to my OS/Arch, but feel free to do a pre-release and ask for feedback in those issues.
Build seems to work fine on my machine:
```
> goreleaser release --snapshot --clean
• skipping announce, publish and validate...
• cleaning distribution directory
• loading environment variables
• getting and validating git state
• git state                                      commit=cbe0aef1d6c8bc8c331d8f6b4d8df554931a876d branch=feat/support-android-arm …
```
=> feat: add android arm64 build

ui/keys/prKeys.go
While working on the docs of some undocumented features/shortcuts, I noticed that the `?` command helper has some inconsistencies with two of the commands.
I updated the 2 commands descriptions that used capital letters to be all lower case like the other descriptions.
Tested it locally
=> docs: consistent formatting in builtin description

docs/content/getting-started/keybindings/selected-pr.md
There was 3 PR features undocumented: update, approve and watch. 
Ran the docs locally.
=> docs: add pr keybindings missing docs

docs/data/schemas/defaults.yaml, ui/ui.go
=> feat: allow disabling refetch interval with 0 value

ui/components/issuesidebar/activity.go, ui/components/issuesidebar/issuesidebar.go, ui/components/prsidebar/activity.go, ui/components/prsidebar/prsidebar.go
Previously, these static regexs were being compiled each time the
function is called. The regexs are static, so there's no need to
re-compile them everytime; instead, compile them once globally per
package, and then re-use them when needed. This
reduces the number of allocations made over the life span of the
program; resulting in less active memory use in general, as well as less
garbage collection. Local profiling with parca and a shimmed in pprof
web server show me approx ~20% less in use memory, going from `~8-10MB`
-> `~6-8MB` after changes.
Signed-off-by: TJ Hoplock <t.hoplock@gmail.com>
=> fix: stop compiling static regex in hot path, compile once globally

config/parser.go, data/issueapi.go, data/prapi.go, git/git.go, ui/components/issue/issue.go, ui/components/issuessection/issuessection.go, ui/components/listviewport/listviewport.go, ui/components/pr/pr.go, ui/components/prssection/prssection.go, ui/components/section/section.go, ui/components/table/table.go, ui/ui.go
closes #450
- Append `createdAt` column after the `lastUpdatedAt` column
- Make `createdAt` and `lastUpdatedAt` column title's icon different
=> feat: add CreatedAt column to PR view and Issue view (#450)

ui/components/issuesidebar/issuesidebar.go, ui/components/prsidebar/prsidebar.go
This change causes gh-dash to show a _“Really cancel comment? (Press Ctrl+c/esc again to cancel)”_ confirm-quit prompt when the user is typing a comment or approval and they press Ctrl+c/esc — similar to the existing confirm-cancel prompt that gh-dash shows when the user has hit q/esc to exit from gh-dash itself.
I ran `make test` (`go test -v ./...`), to ensure this change didn’t regress any existing tests.
Otherwise, I just tested by manually by building this branch and then in PR dashboard and issue dashboard, using the `c` shortcut to open the comment-entry UI, and in the PR dashboard, using the `v` shortcut to open the approval-entry UI.
Comment-entry UI:
---
Approval-entry UI:
=> feat: show confirm-cancel prompt for comments and approvals

README.md, config/parser.go, docs/content/_index.md, docs/content/getting-started/smartfiltering.md, docs/data/schemas/gh-dash.yaml, ui/common/styles.go, ui/components/issuessection/issuessection.go, ui/components/prssection/prssection.go, ui/components/section/section.go, ui/keys/issueKeys.go, ui/keys/prKeys.go
If the current directory from which you launched `gh-dash` is a clone of a GitHub repo, this change causes your PR/issue sections to be further “smartly” auto-filtered down to only the PRs/issues for the remote repo tracked by the clone directory from which you launched `gh-dash`.
Implements what’s proposed in https://github.com/dlvhdr/gh-dash/discussions/309.
In more detail, here’s how it works:
By default, if the directory you launch `gh-dash` from is a clone of a remote GitHub repo (or if you have the `GH_REPO` environment variable set to a particular remote), then for any of your PR sections and issue sections with `filters` values in your configuration that don’t have an explicit `repo:` field, `gh-dash` adds a `repo:<RepoName>` field to the search-bar value for them (where …
=> feat: smart filtering of PRs/issues to remote tracked by current directory

ui/components/issuesidebar/issuesidebar.go, ui/components/prsidebar/prsidebar.go, ui/components/prssection/checkout.go, ui/components/prssection/diff.go, ui/components/prssection/watchChecks.go, ui/tasks.go, ui/ui.go
Closes #527.
Run `make run` with no configuration. No crash when press any keys on PRs and Issues view.
=> fix: missing nil pointer check on PRs and Issues view #527

config/parser.go, docs/content/getting-started/keybindings/selected-pr.md, docs/data/schemas/defaults.yaml, ui/components/prsidebar/prsidebar.go
This change makes it possible to configure the prefilled message used when approving a pull request. This was raised in this discussion post: https://github.com/dlvhdr/gh-dash/discussions/512
Running locally with `make run`, I configured the `.gh-dash.yaml` in this repo to use different values of `defaults.prApproveComment` and observed the prefilled message in the GitHub UI (or lack of one when `defaults.prApproveComment` was set to empty string).
=> feat: make PR approve comment configurable

config/parser.go, config/utils.go, ui/common/styles.go, ui/keys/branchKeys.go, ui/keys/issueKeys.go, ui/keys/keys.go, ui/keys/prKeys.go
This adds the feature of showing the custom keybindings in the help menu. When the custom keybinding is extended with a `name` key, it will render that, otherwise it will use the command itself.
Example:
```yaml
- key: g
command: >
cd {{.RepoPath}} && lazygit
name: lazygit
```
=> feat: show custom keybindings in the help menu

ui/components/inputbox/inputbox.go
This PR sets the character limit for all text boxes in gh-dash to 65536 characters.
While it is possible to set this field (CharLimit) to unlimited (-1), 65536 seems like a sensible default: on GitHub, (almost) all text content supplied through their API is limited by 65536 characters.
Currently, the limit for all textboxes in gh-dash is 400 characters. 
This may seem like a bit of a nitpick, though I've run into the issue myself where I was typing away and ran out of space, only to submit the comment, open the issue/pr in the browser and finish my comment by editing it. This is bad UX IMO.
Closes #517
See: https://github.com/orgs/community/discussions/27190
=> feat: set proper inputbox limit (pr/issue)

ui/keys/keys.go, ui/ui.go
This is a re-do of https://github.com/dlvhdr/gh-dash/pull/565 without the default bindings, and tested to work just via config.
When opening a browser, GNOME things have a tendency to spew messages to stderr which corrupts the gh-dash display.  Nothing made it possible to get a display which then restored the output, the entry area, etc.
A screen redraw command is useful for "something has happened, it shouldn't have, we know it shouldn't have, but that's life, go ahead and redraw please".  This has traditionally been bound to Ctrl-L; but unlike dlvhdr/gh-dash#565 it is not bound in this commit, leaving folks to opt-in via local configuration.
The bubbletea internals appear to have a `repaintMsg{}` but I couldn't figure out how to just send that.  The lightest-weight option I found was to …
=> feat: add redraw builtin key-binding, unbound

data/prapi.go, ui/components/prsidebar/files.go
This PR fixes the shown number of commits in the sidebar of a Pull Request.
I just tested this manually by running the following commands:
```
go build .
./gh-dash -c ~/.config/gh-dash/config.yml
```
Before
After
=> Fix Number of Commits in PR Sidebar
